---

# configure replication for master

- block: 
    - name: "master allow connect from nodes"
      community.postgresql.postgresql_pg_hba:
        dest: "{{ pg_hba }}"
        contype: host
        databases: replication
        users: postgres
        address: "192.168.121.106/24" #todo: automate getting ip-address
        method: md5
        create: true
      notify: restart postgres

    # need restart posgtres before node try connects to master
    - name: Flush handlers
      meta: flush_handlers

  when: inventory_hostname in groups['group_postgres_master']