---

# configure replication for master

- block: 
    - name: "master allow connect from nodes"
      community.postgresql.postgresql_pg_hba:
        dest: "{{ pg_hba }}"
        contype: host
        databases: replication
        users: postgres
        address: "{{ hostvars['postgres-node1']['ansible_default_ipv4']['address'] }}/24"
        method: md5
        create: true
      notify: restart postgres # todo: loop via all nodes

    # need restart posgtres before node try connects to master
    - name: Flush handlers
      meta: flush_handlers

  when: inventory_hostname in groups['group_postgres_master']