---

- name: Install postgres, configure replication
  hosts: group_postgres
  become: true

  vars:
    pg_hba: /etc/postgresql/13/main/pg_hba.conf
    pg_conf: /etc/postgresql/13/main/postgresql.conf
    pg_db_path: /var/lib/postgresql/13/

  roles:
    - shared-roles/set-timezone
    - install
    - replication-all
    - replication-master
    - replication-nodes

  handlers:
    - name: 'restart postgres'
      ansible.builtin.service:
        name: postgresql
        state: restarted